# Uncomment the next line to define a global platform for your project
# platform :osx, '10.13'

target 'Touchbar Tester' do
	platform :osx, '10.13'
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for macOS Sparkline Demo
  pod 'DSFTouchBar', :path => '../../'
end
